-- AlterTable
ALTER TABLE "AC" ADD COLUMN     "resetPasswordCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "resetPasswordExpire" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ADM" ADD COLUMN     "resetPasswordCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "resetPasswordExpire" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "AM" ADD COLUMN     "resetPasswordCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "resetPasswordExpire" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Decideur" ADD COLUMN     "resetPasswordCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "resetPasswordExpire" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SADM" ADD COLUMN     "resetPasswordCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "resetPasswordExpire" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
